---
- name: Configure host.
  hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - config.yml

  tasks:
    - name: Setup apt packages
      import_role:
        name: apt
      when: update_packages

    - import_tasks: tasks/asdf.yml
      tags: ['asdf']

    - import_tasks: tasks/nvim.yml
      tags: ['nvim']

    - import_tasks: tasks/kitty.yml
      #when: update_packages
      tags: ['kitty']

    - import_tasks: tasks/dot-files.yml
      tags: ['dotfiles']